### ISSUE TITLE
Surface Pro 9 still gets stuck on shutdown

### ISSUE THREAD

**Issue by petm5** [linux-surface/surface-shutdown#1]
I built and `modprobe`d this module, but my Surface still gets stuck when I try to shut it down.

Is this module functional yet or is it still a work-in-progress? Do I need to set anything in sysfs for it to work?

**Comment by qzed** [comment]
It's for testing things. It does not make shutdown work and we might remove the module in the future as the issue can't be fixed by a module. Se https://github.com/linux-surface/linux-surface/issues/1058 for a discussion of the issue.
